=== agilan2001/WebTech-Assignments/Assignment-11/HireDetails.dtd
<!ELEMENT HireDetails (HireItem+)>
<!ELEMENT HireItem (CustomerName,hiredate,ProductDetails)>
<!ELEMENT CustomerName (firstname,lastname)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT hiredate (day,month,year)>
<!ELEMENT day (#PCDATA)>
<!ELEMENT month (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT ProductDetails (product,price)>
<!ELEMENT product (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ATTLIST HireItem id CDATA #REQUIRED>

=== agilan2001/WebTech-Assignments/Assignment-11/HireDetails(DTD).xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE HireDetails SYSTEM "HireDetails.dtd">
<HireDetails>
    <HireItem id="111">
        <CustomerName>
            <firstname>Kelly</firstname>
            <lastname>Grace</lastname>
        </CustomerName>
        <hiredate>
            <day>15</day>
            <month>October</month>
            <year>2005</year>
        </hiredate>
        <ProductDetails>
            <product>Printer</product>
            <price>111</price>
        </ProductDetails>
    </HireItem>
    <HireItem id="112">
        <CustomerName>
            <firstname>Longo</firstname>
            <lastname>Mich</lastname>
        </CustomerName>
        <hiredate>
            <day>17</day>
            <month>January</month>
            <year>2004</year>
        </hiredate>
        <ProductDetails>
            <product>Printer</product>
            <price>111</price>
        </ProductDetails>
    </HireItem>
    <HireItem id="114">
        <CustomerName>
            <firstname>Mohammed</firstname>
            <lastname>Shahul</lastname>
        </CustomerName>
        <hiredate>
            <day>5</day>
            <month>November</month>
            <year>2005</year>
        </hiredate>
        <ProductDetails>
            <product>Television</product>
            <price>115</price>
        </ProductDetails>
    </HireItem>
</HireDetails>
